### ISSUE TITLE
sử dụng @ trong modulealias bị xoá file + update api lên đi ông ơi

### ISSUE THREAD

**Issue by roxtigger2003** [VNBot-Developers/annie#4]
sử dụng @ trong modulealias nó tự xoá file ông ơi, với cả update api lên đi

**Comment by lequanglam** [comment]
_gõ @ trong require để làm gì nhỉ, dùng ./ không được à?_
hmm

**Comment by roxtigger2003** [comment]
tui chịu, chắc để cho nó gọn ¯\_(ツ)_/¯

**Comment by lequanglam** [comment]
nah, thay hết thành `./` giùm đi
mù mắt vc

**Comment by roxtigger2003** [comment]
ok bên tui fork thay xong hết rồi chỉ còn mỗi lỗi 404 đợi ông fix nữa là được

**Comment by lequanglam** [comment]
lỗi 404 thì tạm thời ông thay qua repo `fca-unofficial` của tôi rồi xài 
```js
api.markAsSeen(function (err) {
    if (err) console.log(err);
    //markAsRead ở đây
});
```

**Comment by roxtigger2003** [comment]
thề luôn code ông này chả biết thay ở đâu cơ rối vcl :/

**Comment by roxtigger2003** [comment]
giúp tôi với ông :(

**Comment by lequanglam** [comment]
ông thấy api.markAsRead chỗ nào thì cứ thay hết thôi.

**Comment by roxtigger2003** [comment]
> ông thấy api.markAsRead chỗ nào thì cứ thay hết thôi.

![A7172D2C-3047-4E3A-86B7-041993FBF225](https://user-images.githubusercontent.com/36947924/77624299-2ec87500-6f74-11ea-9bf9-12e52a90d171.jpeg)
nó ra lỗi này ông ơi, giúp tui phát này với 🙏

**Comment by lequanglam** [comment]
cái đấy thì có thể acc của ông bị zucc rồi 🤔 check lại trên trình duyệt đi

**Comment by roxtigger2003** [comment]
mà ông ơi, không biết cái module ông bị gì không nhưng lâu lâu nó không trả về cái sendmessage mà khiến app crash luôn, ông lại giúp tui với 
![C3199EDD-00CF-4D24-9E3A-7B0992120F8F](https://user-images.githubusercontent.com/36947924/77820798-7f2c0800-7117-11ea-83d6-841c8f138069.jpeg)

**Comment by lequanglam** [comment]
ông chụp giùm tôi full stack trace chứ nhìn kiểu đó tôi biết chỗ nào lỗi?
